version: '2'
services:
  master:
    image: "fidato/hadoop-ubuntu:latest"
    stdin_open: true
    tty: true
    container_name: master
    ports:
      - "8088:8088"
      - "50070:50070"
  slave1:
    image: "fidato/hadoop-ubuntu:latest"
    stdin_open: true
    tty: true
    container_name: slave1
  slave2:
    image: "fidato/hadoop-ubuntu:latest"
    stdin_open: true
    tty: true
    container_name: slave2
  slave3:
    image: "fidato/hadoop-ubuntu:latest"
    stdin_open: true
    tty: true
    container_name: slave3
