version: '2'
services:
  master:
    image: "fidato/hadoop-ubuntu:latest"
    stdin_open: true
    tty: true
    container_name: master
  slaves1:
    image: "fidato/hadoop-ubuntu:latest"
    stdin_open: true
    tty: true
    container_name: slaves1
  slaves2:
    image: "fidato/hadoop-ubuntu:latest"
    stdin_open: true
    tty: true
    container_name: slaves2
